version: '3.8'
services:
  grafana:
    container_name: container-grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
 
  prometheus:
    container_name: container-prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
 
  node-exporter:
    container_name: container-node-exporter
    image: prom/node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
 
volumes:
  grafana-data:
  prometheus-data: